### ISSUE TITLE
Write Video processing javascript algorithm

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/insights#12]
- [x] Algorithm - Examples: Licence Plate Recognition, Face Detection, **Cat Detection**
- [x] Use a small video (so we don't exceed the env limitations)
- [x] Report the env limitations(identify what is possible and what not)

**Comment by mariacarmina** [comment]
@AnaLoznianu, regarding `Cat Detection`, should the algorithm return the number of identified cats from the video or other characteristics (such as breed or something else)? I was thinking that the algo should fetch only the number of cats. Can we agree on this? Thank you.

**Comment by LoznianuAnamaria** [comment]
@mariacarmina The algorithms I've included here are mere suggestions. You are free to pick what you believe aligns better with the task and effectively showcases the capabilities. I trust your judgment. 😉

**Comment by mariacarmina** [comment]
Thank you for explanations. I'll go with no. of cats for `Cat Detection` algo.

**Comment by mariacarmina** [comment]
UPDATE: I did some research and I'll better go with `Human Face Detection` and for that I'll use `face-api.js` which has built-in methods for this algorithm and it's easy to use.
The algorithm should return a video with the human faces included in rectangles/boxes.

**Comment by mariacarmina** [comment]
UPDATE: Because of C2D limitations (we don't support GPUs and if we want to, we need to do modifications in C2D code to add `taint`, which I consider out of scope for the moment), the video needs to be very short like 3 secs. I have published a 3 secs video and it processed pretty well. I'll attach here the final version of what C2D returned. The algorithm is successfully integrated in insights as well.
[output.mp4](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUdiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed31a0916c89754418772e47003189a72aeca96d/output%20%282%29.mp4)
